### ISSUE TITLE
exposed type considered harmful

### ISSUE THREAD

**Issue by nrnrnr** [BurntSushi/clibs#2]
If `DSQueue` is supposed to be opaque, then there is no reason to expose its representation in the header, is there?

**Comment by BurntSushi** [comment]
Yup. When I wrote this, I don't think I realized there was anything special about an opaque type in C other that simply declaring it be opaque. [This was fixed.](https://github.com/BurntSushi/clibs/commit/2803e51130d4d8bfc65ec35924178e78b6571370)
