### ISSUE TITLE
integration with clib(1)

### ISSUE THREAD

**Issue by stephenmathieson** [BurntSushi/clibs#4]
i like the name, haha.  checkout our project [clibs/clib](https://github.com/clibs/clib).

thoughts on merging these libs into the clibs orig?  i'd happy give you create access.

**Comment by BurntSushi** [comment]
I'm definitely interested. As it is, these libs are just sitting here unused as far as I can tell.

I see that you already have a flag parsing library though, is it worthwhile to have two? (I just checked out `commander`. It looks very nice. I'd probably use it in lieu of my own. So maybe that answers that question.)

I scanned the package list and it looks like you don't have hash tables, vectors or channels. So maybe I should split those into three separate libraries? Is there a way to express dependencies between libraries? (e.g., The hash table uses a vector.)

**Comment by BurntSushi** [comment]
Nevermind. I see you already have a hash table library called `hash`. So that leaves vector and channels. (Unless I'm missing vector somewhere too.)

**Comment by stephenmathieson** [comment]
there's nothing in the clibs namespace for thread-safe queues, etc.  i've got [batch.c](https://github.com/stephenmathieson/batch.c), but it's buggy/unfinished.  if you like, i'll add you to the org and you can add add whatever you like :)

> ..is it worthwhile to have two?

can't hurt -- having options is always a good thing :)

**Comment by BurntSushi** [comment]
Great. Add me and I'll see what I come up with. I'll make the channel lib a priority since I see that as the most useful. I may not get to it for a couple weeks though---currently transitioning between jobs.

**Comment by stephenmathieson** [comment]
> Is there a way to express dependencies between libraries? (e.g., The hash table uses a vector.)

yes, the docs are incomplete.  just specify "dependencies" in your lib's package.json like [this](https://github.com/clibs/clib/blob/master/package.json#L5-L16)

**Comment by BurntSushi** [comment]
Ah great! Thank you.

**Comment by stephenmathieson** [comment]
just added you.  no worries on the timeline!
